# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/daniilparfenov/Documents/software/game/gameCpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/daniilparfenov/Documents/software/game/gameCpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/daniilparfenov/Documents/software/game/gameCpp/CMakeFiles /Users/daniilparfenov/Documents/software/game/gameCpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/daniilparfenov/Documents/software/game/gameCpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gameCpp

# Build rule for target.
gameCpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gameCpp
.PHONY : gameCpp

# fast build rule for target.
gameCpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameCpp.dir/build.make CMakeFiles/gameCpp.dir/build
.PHONY : gameCpp/fast

field.o: field.cpp.o
.PHONY : field.o

# target to build an object file
field.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameCpp.dir/build.make CMakeFiles/gameCpp.dir/field.cpp.o
.PHONY : field.cpp.o

field.i: field.cpp.i
.PHONY : field.i

# target to preprocess a source file
field.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameCpp.dir/build.make CMakeFiles/gameCpp.dir/field.cpp.i
.PHONY : field.cpp.i

field.s: field.cpp.s
.PHONY : field.s

# target to generate assembly for a file
field.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameCpp.dir/build.make CMakeFiles/gameCpp.dir/field.cpp.s
.PHONY : field.cpp.s

game.o: game.cpp.o
.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameCpp.dir/build.make CMakeFiles/gameCpp.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i
.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameCpp.dir/build.make CMakeFiles/gameCpp.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s
.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameCpp.dir/build.make CMakeFiles/gameCpp.dir/game.cpp.s
.PHONY : game.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameCpp.dir/build.make CMakeFiles/gameCpp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameCpp.dir/build.make CMakeFiles/gameCpp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameCpp.dir/build.make CMakeFiles/gameCpp.dir/main.cpp.s
.PHONY : main.cpp.s

mpc.o: mpc.cpp.o
.PHONY : mpc.o

# target to build an object file
mpc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameCpp.dir/build.make CMakeFiles/gameCpp.dir/mpc.cpp.o
.PHONY : mpc.cpp.o

mpc.i: mpc.cpp.i
.PHONY : mpc.i

# target to preprocess a source file
mpc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameCpp.dir/build.make CMakeFiles/gameCpp.dir/mpc.cpp.i
.PHONY : mpc.cpp.i

mpc.s: mpc.cpp.s
.PHONY : mpc.s

# target to generate assembly for a file
mpc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gameCpp.dir/build.make CMakeFiles/gameCpp.dir/mpc.cpp.s
.PHONY : mpc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gameCpp"
	@echo "... field.o"
	@echo "... field.i"
	@echo "... field.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mpc.o"
	@echo "... mpc.i"
	@echo "... mpc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

